// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GALV_ActionIndicatorsMZ","status":true,"description":"(v.1.0) Display an icon when the player is able to interact with an event. View help for comment tag.","parameters":{"yOffset":"-10","zPosition":"5","autoHide":"true","iconOpacity":"200"}}
];
