// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GALV_ActionIndicatorsMZ","status":true,"description":"(v.1.0) Display an icon when the player is able to interact with an event. View help for comment tag.","parameters":{"yOffset":"-10","zPosition":"5","autoHide":"true","iconOpacity":"200"}},
{"name":"JLP_CustomKeyboardInput","status":true,"description":"[Version 1.0]","parameters":{"Debug?":"true","Tab":"[\"9\"]","Okay/Confirm":"[\"13\",\"32\",\"90\"]","Shift":"[\"16\"]","Control":"[\"17\"]","Escape/Back":"[\"8\", \"27\", \"45\", \"88\", \"96\"]","Page Up":"[\"33\", \"81\"]","Page Down":"[\"34\", \"69\"]","Left":"[\"37\", \"65\", \"100\"]","Up":"[\"38\", \"87\", \"104\"]","Right":"[\"39\", \"68\", \"102\"]","Down":"[\"40\", \"83\", \"98\"]","Debug Key":"[\"120\"]"}}
];
